alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias n4-mount="go-mtpfs ~/mnt &"
alias n4-umount="fusermount -u ~/mnt"
alias arch-wiki="xdg-open 'https://wiki.archlinux.org'"
alias aur="xdg-open 'https://aur.archlinux.org'"
alias l10="du -sh * | sort -rh | head -10"
alias lsw="watch -n 0.5 -c 'tree -a'"
alias csgo="xrun steamlaunch 730"
