# Shadows
shadow = true;
shadow-radius = 12;
shadow-opacity = .5;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-exclude = [
    "window_type = 'dock'",
    # Fix shadowed transparency around menus in Firefox ...
    "class_g ?= 'firefox' && (window_type = 'utility' || window_type = 'popup_menu')",
    # ... and Chrome (which can't be matched by class or name)
    "argb && override_redirect && window_type = 'menu'"
];
clip-shadow-above = [
    "window_type = 'dock'",
    "class_i = 'xmonad-prompt'"
];

# Fading
fading = true;
fade-in-step = 0.025;
fade-out-step = 0.025;
fade-delta = 6;
fade-exclude = [
    "window_type = 'normal' && !override_redirect",
    "window_type *= 'menu'"
];

# Corners
corner-radius = 16;
rounded-corners-exclude = [
    "window_type != 'normal' && window_type != 'splash' && window_type != 'dialog'",
    "window_type = 'normal' && override_redirect",
];

# General Settings
backend = "glx";
vsync = true;
use-ewmh-active-win = true;
