[general]
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[window]
dynamic_padding = true
resize_increments = true

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 5

[scrolling]
history = 8192
multiplier = 5

[font]
size = 12.0

[font.offset]
x = 1
y = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
blink_timeout = 0
thickness = 0.0

[cursor.style]
blinking = "Always"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

